# Generated by Django 3.0.5 on 2020-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=100)),
                ('race_category', models.CharField(max_length=50)),
                ('race_distance', models.IntegerField()),
                ('race_deniv', models.IntegerField()),
                ('race_time', models.CharField(max_length=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
