# Generated by Django 3.0.5 on 2020-04-19 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_date',
            field=models.DateField(default=datetime.date(2020, 4, 19)),
        ),
    ]
