# Generated by Django 3.0.5 on 2020-04-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
