# Generated by Django 3.0.5 on 2020-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_race_race_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_category',
            field=models.CharField(choices=[('TR', 'Trail'), ('UL', 'Ultra'), ('MA', 'Marathon'), ('SE', 'Semi'), ('AU', 'Autre')], default='TR', max_length=2),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_deniv',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_distance',
            field=models.SmallIntegerField(),
        ),
    ]
