# Generated by Django 3.0.5 on 2020-04-20 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20200419_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='race_deniv',
            new_name='deniv',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='race_distance',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='race_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='race_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='race_date',
        ),
        migrations.AddField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 20)),
        ),
    ]
